### ISSUE TITLE
luci-app-pushbot的在线设备列表界面表格显示异常

### ISSUE THREAD

**Issue by fonlan** [gngpp/luci-theme-design#121]
正常应该是如下表格：
![屏幕截图 2024-01-07 170949](https://github.com/gngpp/luci-theme-design/assets/7898348/fb2047bc-cc4d-4aeb-8ee7-6fe2efe122c1)
使用本主题后：
![屏幕截图 2024-01-07 171109](https://github.com/gngpp/luci-theme-design/assets/7898348/5b33aa64-ed9a-4b50-ac32-829a45181f73)

和其他主题对比后应该是css中缺少以下定义以及相关的样式优化
```css
.table {
    display: table;
}
.tr {
    display: table-row;
}
.th .td {
    display: table-cell;
}
```
